version: '3.5'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: tazim
    ports:
      - '8000:8000'
    volumes:
      - .:/server
      - /server/node_modules
  